services:
  db:
    image: postgres:16
    container_name: motoboys-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motoboys
    ports:
      - "5432:5432"
    volumes:
      - motoboys_pgdata:/var/lib/postgresql/data

volumes:
  motoboys_pgdata:
